environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm ci
before_test:
  - node --version
  - npm --version
test_script:
  - npm test
build: off
